/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.grafica;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author dam2
 */
public class Calculadora extends javax.swing.JFrame {

    double op1, op2;

    /**
     * Creates new form Contenedor
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        GrupoEleccionSUMARESTA = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txValor1bt = new javax.swing.JTextField();
        txValor2bt = new javax.swing.JTextField();
        btSumar = new javax.swing.JButton();
        btRestar = new javax.swing.JButton();
        btMulti = new javax.swing.JButton();
        btDivi = new javax.swing.JButton();
        LbResultbt = new javax.swing.JLabel();
        lbResultadobt = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btIgualrd = new javax.swing.JButton();
        radioSuma = new javax.swing.JRadioButton();
        radioResta = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        cDecims = new javax.swing.JCheckBox();
        txValor1rd = new javax.swing.JTextField();
        txValor2rd = new javax.swing.JTextField();
        lbResultadord = new javax.swing.JLabel();
        LbResultbt1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btIgualcb = new javax.swing.JButton();
        CbOpciones = new javax.swing.JComboBox();
        txValor1cb = new javax.swing.JTextField();
        txValor2cb = new javax.swing.JTextField();
        lbResultadocb = new javax.swing.JLabel();
        LbResultcb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        txValor1bt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txValor1btFocusLost(evt);
            }
        });
        txValor1bt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txValor1btKeyTyped(evt);
            }
        });

        txValor2bt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txValor2btFocusLost(evt);
            }
        });
        txValor2bt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txValor2btKeyTyped(evt);
            }
        });

        btSumar.setText("+");
        btSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSumarActionPerformed(evt);
            }
        });

        btRestar.setText("-");
        btRestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRestarActionPerformed(evt);
            }
        });

        btMulti.setText("X");
        btMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMultiActionPerformed(evt);
            }
        });

        btDivi.setText("/");
        btDivi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDiviActionPerformed(evt);
            }
        });

        LbResultbt.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lbResultadobt.setText("Resultado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btDivi, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMulti, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRestar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txValor1bt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(txValor2bt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResultadobt)
                    .addComponent(LbResultbt, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txValor2bt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txValor1bt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btSumar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRestar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btMulti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btDivi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(lbResultadobt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbResultbt, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Boton", jPanel1);

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btIgualrd.setText("=");

        GrupoEleccionSUMARESTA.add(radioSuma);
        radioSuma.setSelected(true);
        radioSuma.setText("Sumar");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, radioSuma, org.jdesktop.beansbinding.ELProperty.create("Suma"), radioSuma, org.jdesktop.beansbinding.BeanProperty.create("actionCommand"));
        bindingGroup.addBinding(binding);

        GrupoEleccionSUMARESTA.add(radioResta);
        radioResta.setText("Restar");
        radioResta.setActionCommand("Resta");

        GrupoEleccionSUMARESTA.add(jRadioButton1);
        jRadioButton1.setText("Multiplicar");
        jRadioButton1.setActionCommand("Multiplica");

        GrupoEleccionSUMARESTA.add(jRadioButton2);
        jRadioButton2.setText("Dividir");
        jRadioButton2.setActionCommand("Dividi");

        cDecims.setText("Decimales");

        txValor1rd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txValor1rdFocusLost(evt);
            }
        });
        txValor1rd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txValor1rdKeyTyped(evt);
            }
        });

        txValor2rd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txValor2rdFocusLost(evt);
            }
        });
        txValor2rd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txValor2rdKeyTyped(evt);
            }
        });

        lbResultadord.setText("Resultado");

        LbResultbt1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txValor1rd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radioSuma)
                            .addComponent(radioResta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txValor2rd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(cDecims))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButton2)
                            .addComponent(jRadioButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btIgualrd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResultadord)
                    .addComponent(LbResultbt1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txValor2rd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txValor1rd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioSuma, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cDecims)
                    .addComponent(radioResta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(btIgualrd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbResultadord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbResultbt1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Radio", jPanel2);

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btIgualcb.setText("=");
        btIgualcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgualcbActionPerformed(evt);
            }
        });

        CbOpciones.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sumar", "Restar", "Dividir", "Multiplicar" }));
        CbOpciones.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                CbOpcionesPropertyChange(evt);
            }
        });

        txValor1cb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txValor1cbFocusLost(evt);
            }
        });
        txValor1cb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txValor1cbKeyTyped(evt);
            }
        });

        txValor2cb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txValor2cbFocusLost(evt);
            }
        });
        txValor2cb.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txValor2cbKeyTyped(evt);
            }
        });

        lbResultadocb.setText("Resultado");

        LbResultcb.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btIgualcb)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txValor1cb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(CbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(txValor2cb, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbResultadocb)
                    .addComponent(LbResultcb, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(CbOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txValor1cb, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txValor2cb, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btIgualcb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(lbResultadocb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbResultcb, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Combo", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSumarActionPerformed
        if (!error()) {
            LbResultbt.setText((op1 + op2) + "");
        }
    }//GEN-LAST:event_btSumarActionPerformed

    private void btRestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRestarActionPerformed
        if (!error()) {
            LbResultbt.setText((op1 - op2) + "");
        }
    }//GEN-LAST:event_btRestarActionPerformed

    private void btMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMultiActionPerformed
        if (!error()) {
            LbResultbt.setText((op1 * op2) + "");
        }
    }//GEN-LAST:event_btMultiActionPerformed

    private void btDiviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDiviActionPerformed
        if (!error()) {
            LbResultbt.setText((op1 / op2) + "");
        }
    }//GEN-LAST:event_btDiviActionPerformed

    private void txValor1btKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txValor1btKeyTyped
        txValor1bt.setBackground(Color.white);
        txValor1bt.setForeground(Color.black);
    }//GEN-LAST:event_txValor1btKeyTyped

    private void txValor2btKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txValor2btKeyTyped
        txValor2bt.setBackground(Color.white);
        txValor2bt.setForeground(Color.black);
    }//GEN-LAST:event_txValor2btKeyTyped

    private void txValor1btFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txValor1btFocusLost
        boolean error = false;
        try {
            op1 = Double.parseDouble(txValor1bt.getText());
        } catch (Exception w) {
            txValor1bt.setBackground(Color.red);//Cambia el color de fondo
            txValor1bt.setForeground(Color.white);//Cambia el color del texto
            error = true;
        }
    }//GEN-LAST:event_txValor1btFocusLost

    private void txValor2btFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txValor2btFocusLost
        boolean error = false;
        try {
            op2 = Double.parseDouble(txValor2bt.getText());
        } catch (Exception w) {
            txValor2bt.setBackground(Color.red);//Cambia el color de fondo
            txValor2bt.setForeground(Color.white);//Cambia el color del texto
            error = true;
        }
    }//GEN-LAST:event_txValor2btFocusLost

    private void btIgualcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btIgualcbActionPerformed
        if (!error()) {
            /*if (!cDecims.isSelected()) {
                op1=Math.floor(op1);
                op2=Math.floor(op2);
            }*/
            switch (GrupoEleccionSUMARESTA.getSelection().getActionCommand()) {
                //HEMOS CONFIGURADO EL ACTION COMMAND EN DISEÑO, BOTON DERECHO SOBRE EL RADIOBUTTON Y PROPIEDADES-->BINDING Y CAMBIAMOS LA CASILLA "ACTIONCOMMAND"
                case "Suma":
                    if(!cDecims.isSelected()){
                        LbResultbt.setText(((int)(op1 + op2))+"");
                    }else{
                        LbResultbt.setText(op1 + op2+"");
                    }
                    break;
                case "Resta":
                    if(!cDecims.isSelected()){
                        LbResultbt.setText(((int)(op1 - op2))+"");
                    }else{
                        LbResultbt.setText(op1 - op2+"");
                    }
                    break;
                case "Multiplica":
                    if(!cDecims.isSelected()){
                        LbResultbt.setText(((int)(op1 * op2))+"");
                    }else{
                        LbResultbt.setText(op1 * op2+"");
                    }
                    break;
                case "Dividi":
                    if(!cDecims.isSelected()){
                        LbResultbt.setText(((int)(op1 / op2))+"");
                    }else{
                        LbResultbt.setText(op1 / op2+"");
                    }
                    break;
            }
        }
    }//GEN-LAST:event_btIgualcbActionPerformed

    private void CbOpcionesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_CbOpcionesPropertyChange
        // PARA EDITAR (AGREGANDO O QUITANDO) COMPONENTES DEL COMBO
    }//GEN-LAST:event_CbOpcionesPropertyChange

    private void txValor1rdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txValor1rdFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txValor1rdFocusLost

    private void txValor1rdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txValor1rdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txValor1rdKeyTyped

    private void txValor2rdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txValor2rdFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txValor2rdFocusLost

    private void txValor2rdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txValor2rdKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txValor2rdKeyTyped

    private void txValor1cbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txValor1cbFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txValor1cbFocusLost

    private void txValor1cbKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txValor1cbKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txValor1cbKeyTyped

    private void txValor2cbFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txValor2cbFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txValor2cbFocusLost

    private void txValor2cbKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txValor2cbKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txValor2cbKeyTyped

    private boolean error() {
        boolean error = false;
        try {
            op1 = Double.parseDouble(txValor1bt.getText());
        } catch (Exception w) {
            txValor1bt.setBackground(Color.red);//Cambia el color de fondo
            txValor1bt.setForeground(Color.white);//Cambia el color del texto
            error = true;
        }
        try {
            op2 = Double.parseDouble(txValor2bt.getText());
        } catch (Exception w) {
            txValor2bt.setBackground(Color.red);
            txValor2bt.setForeground(Color.white);
            error = true;
        }
        if (error) {
            JOptionPane.showMessageDialog(this, "Se ha introducido un valor no numérico", "Error", JOptionPane.ERROR_MESSAGE);
        }
        return error;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CbOpciones;
    private javax.swing.ButtonGroup GrupoEleccionSUMARESTA;
    private javax.swing.JLabel LbResultbt;
    private javax.swing.JLabel LbResultbt1;
    private javax.swing.JLabel LbResultcb;
    private javax.swing.JButton btDivi;
    private javax.swing.JButton btIgualcb;
    private javax.swing.JButton btIgualrd;
    private javax.swing.JButton btMulti;
    private javax.swing.JButton btRestar;
    private javax.swing.JButton btSumar;
    private javax.swing.JCheckBox cDecims;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbResultadobt;
    private javax.swing.JLabel lbResultadocb;
    private javax.swing.JLabel lbResultadord;
    private javax.swing.JRadioButton radioResta;
    private javax.swing.JRadioButton radioSuma;
    private javax.swing.JTextField txValor1bt;
    private javax.swing.JTextField txValor1cb;
    private javax.swing.JTextField txValor1rd;
    private javax.swing.JTextField txValor2bt;
    private javax.swing.JTextField txValor2cb;
    private javax.swing.JTextField txValor2rd;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
